// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://docxdhdtcpzihnvfobnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvY3hkaGR0Y3B6aWhudmZvYm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTU2OTEsImV4cCI6MjA2MTczMTY5MX0.4Z7qUIETZ_LcYSA3cpJjWXHYzTDC36aVysJgV4dbIlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);